### PR TITLE
Add skeleton for Help menu

### PR DESCRIPTION
**Pull request by trobbierob**
## Please Add Description
**Added Skeleton for Help menu**

## Detailed commit.
_Add skeleton for Help menu, including SearchView in App Bar_

## Collaborators Merge Master into your branch first always before creating that PR 

# Checklist:
- My code follows the code style of this project.
**I hope...**
 
- My change requires a change to the documentation.
**NA**
 
- I have updated the documentation accordingly.
**NA**

### CODE REVIEW

**Comment by Madonahs** [comment]
@trobbierob I see you have conflicts can you Try merging master into your branch first. Then try the PR 😊

**Comment by trobbierob** [comment]
I will try that out! Thanks!

**Comment by Madonahs** [comment]
@trobbierob you are welcome, i can help if you want.

**Comment by trobbierob** [comment]
I'll pull you in if I fail at least two more times, haha.

**Comment by Madonahs** [comment]
Awesome.

**Pull request closed without merging**
