### PR TITLE
Searchview

### PR DESCRIPTION
**Pull request by trobbierob**
## Please Add Description
I updated the SearchView with the code from the HelpActivity. You can't search for anything just yet, but you'll see search suggestions. I saw you wanted me to add the search to the settings, so I can try that also.

# Checklist:
- I have updated the documentation accordingly.
I'll just need to make a minor change to the README for the MaterialSearchView source.

### CODE REVIEW

**Comment by Madonahs** [comment]
Awesome, let me check it out,

**Comment by Madonahs** [comment]
Noticed a bug, can you try turning the dark theme on  and off on your branch.

**Comment by trobbierob** [comment]
I’ll take a look when I get home.

**Comment by trobbierob** [comment]
Figured out the issue with the dark theme. The toolbar didn't share the same toolbar color change with the others. Working on the backToMain button.

**Pull request merged**
